# Generated by Django 3.2.16 on 2023-01-09 12:00

from django.db import migrations, models
import django.db.models.deletion
import v1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('platform_fee', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=v1.models.generate_code, editable=False, max_length=7)),
                ('max_guests', models.IntegerField()),
                ('num_bathroom', models.IntegerField()),
                ('is_pet_friendly', models.BooleanField(default=True)),
                ('cleaning_fee', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=v1.models.generate_code, editable=False, max_length=7)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.immobile'),
        ),
    ]
